<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\ClassMetadata;
use ShopBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository implements ArticleRepositoryInterface
{
    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new ClassMetadata(Article::class));
    }

    public function createAnArticle(Article $article)
    {
        $this->_em->persist($article);
        $this->_em->flush();
    }

    public function editAnArticle(Article $oldArticleData, Article $newArticleData)
    {
        $oldArticleData->setTitle($newArticleData->getTitle());
        $oldArticleData->setContent($newArticleData->getContent());
        $this->_em->flush();
    }
}
