<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\Mapping\ClassMetadata;
use ShopBundle\Entity\Comment;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository implements CommentRepositoryInterface
{

    public function __construct(EntityManagerInterface $em)
    {
        parent::__construct($em, new ClassMetadata(Comment::class));
    }

    public function createComment(Comment $comment)
    {
        $this->_em->persist($comment);
        $this->_em->flush();
    }

    public function editComment(Comment $oldComment, Comment $newComment)
    {
        $oldComment->setCommentText($newComment->getCommentText());
        $this->_em->flush();
    }

    public function deleteComment(Comment $comment)
    {
        $this->_em->remove($comment);
        $this->_em->flush();
    }
}
