<?php

namespace ShopBundle\Repository;

/**
 * ForgottenUserPassRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForgottenUserPassRepository extends \Doctrine\ORM\EntityRepository
{
}
